---
- name: Configure oh-my-zsh with plugins
  hosts: all
  tasks:
    - name: Check if zsh is installed
      command: which zsh
      register: zsh_check
      ignore_errors: yes

    - name: Install zsh
      apt:
        name: zsh
        state: present
      when: zsh_check.rc != 0

    - name: Download ZSH archive
      get_url:
        url: https://pub-75e01a31d4044cfbad6ee9f5d35e694f.r2.dev/oh-my-zsh.tar
        dest: "{{ ansible_env.HOME }}/oh-my-zsh.tar"

    - name: Extract ZSH archive
      unarchive:
        src: "{{ ansible_env.HOME }}/oh-my-zsh.tar"
        dest: "{{ ansible_env.HOME }}"
        remote_src: yes

    - name: Delete ZSH archive
      file:
        path: "{{ ansible_env.HOME }}/oh-my-zsh.tar"
        state: absent
